# Generated by Django 5.0.6 on 2024-05-26 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_alter_classroom_malophoc'),
        ('score', '0002_finalscore_scoreformular'),
        ('student', '0006_alter_class_student_malophoc'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColumnCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TenCotDiem', models.CharField(max_length=50)),
                ('Code', models.CharField(max_length=50)),
                ('MaLopHoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.classroom')),
            ],
            options={
                'unique_together': {('MaLopHoc', 'TenCotDiem')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='score',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='score',
            name='MaCotDiem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='score.columncode'),
        ),
        migrations.AlterUniqueTogether(
            name='score',
            unique_together={('MaSinhVien', 'MaLopHoc', 'MaCotDiem')},
        ),
    ]
