# Generated by Django 5.0.6 on 2024-05-26 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0004_alter_columncode_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='columncode',
            name='Code',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
