# Generated by Django 5.0.6 on 2024-05-26 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0005_alter_columncode_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='TenThanhPhanDiem',
        ),
    ]
