# Generated by Django 5.0.6 on 2024-05-26 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0006_remove_score_tenthanhphandiem'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='columncode',
            unique_together=set(),
        ),
    ]
