# Generated by Django 5.0.6 on 2024-05-27 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0007_alter_columncode_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoreformular',
            name='is_user_modified',
            field=models.BooleanField(default=False),
        ),
    ]
