# Generated by Django 5.0.6 on 2024-05-27 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0008_scoreformular_is_user_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalscore',
            name='TenCotDiem',
            field=models.CharField(default='Tổng kết', max_length=50),
        ),
    ]
