# Generated by Django 5.0.6 on 2024-05-27 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0009_finalscore_tencotdiem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoreformular',
            name='Formular',
            field=models.CharField(default='', max_length=100),
        ),
    ]
